server:
  port: 8070

notipush:
  database:
    ip: 123.57.73.105
    port: 3306
    username: root
    password: lixianglan123

spring:
  datasource:
    url: jdbc:mysql://${notipush.database.ip}:${notipush.database.port}/austin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${notipush.database.username}
    password: ${notipush.database.password}
    driver-class-name: com.mysql.jdbc.Driver